### PR TITLE
Classification of Units added as a new view

### PR DESCRIPTION
**Pull request by b2ag**
Hi Spooky,

we made some changes to your great project and added a view to show units in more detailed logical groups. We also fixed some minor issues. I've to confess that I'm not good in writing modern CSS (which you can see in the commit). Feel free to remove the shitty stuff and merge the good things.

Best regards,
B2ag

### CODE REVIEW

**Comment by b2ag** [comment]
It's deployed there:
http://b2ag.github.io/unitdb/#/gdi

**Comment by JeroenDeDauw** [comment]
This is really neat!

**Comment by spooky** [comment]
Great job. Got a few notes to consider:
* Love the fixed positioning on the filters - can you apply this styling to the default view as well?
* There's no way to switch between view modes - maybe add a toggle button/buttons somewhere? I was thinking on top of the filters but that will mess up the layout alignment a bit. Other option is after the filters... which is less than perfect in terms of usability. Maybe you have any suggestions/ideas?

Side note, what does GDI stand for?

**Comment by b2ag** [comment]
Hi Spooky,

I would suggest to put a text above the filters saying "Alternative View ->", which switches to a "<- Classic View" in the "GDI" View to toggle URLs. I didn't put in something like this in, because I didn't want to change your view. I can do this eventually, and also add the fixed filters style to your view, but currently I'm short on time. So, be patient.

GDI is our clan-tag in FAF. I choose it, because the thing was a combined effort from me and [gdi]svenni, who motivated this view, defined most of the categories and added the needed extra data for useful sorting and grouping. And yes, it's a reference to C&C ;)

**Comment by IDragonfire** [comment]
Any updates here?

**Comment by spooky** [comment]
Waiting for rebase & some time to spare to actually deploy the merged changes.

**Pull request closed without merging**
