### PR TITLE
Weapons grouping first pass

### LINKED ISSUE #24: consolidate repeated weapons
some units have the same weapons in numbers > 1 (like UEF destroyer gauss cannon) - make these show up as one with doubled stats.

### PR DESCRIPTION
**Pull request by Araamarmorth**
This commit is a first pass to fix #24 "consolidate repeated weapons"

Weapons that are strictly the same are grouped and a field "number of weapons" is added, as can be seen on http://araamarmorth.github.io/unitdb/#/UAA0102,UAA0310,UEL0401

This is not be perfect: weapons slightly different like the fatboy's gauss canons which have a different turret yaw are currently not grouped and the visual needs some work (it's not visible enough for such an important data).

The change in the unit file is made using tools/cleaner.py which was modified for the occasion.

The new functionnality in cleaner.py is the regroup_weapons function (l:285-312) but I also refactored a bit of code, added an header, some comments. This is not complete as I didn't modified the slenderize function which needs it. The sorting function of the new cleaner is slightly more robust which allows more units to be ordered: this could be probelmatic as such: I don't know enough about how exactly you process the units to tell. On my version this created some aberations: some units were misordered and the tech filters didn't work so I didn't run the full process and only loaded the index.json applied the regroup_weapon function and saved back. Yet I couldn't build the from source (cf #35) so it might be good.

The modification in the page is done very simply in app/views/unit.html: this might need an heavy rework of the table structure to look good but for now this introduce the functionality

The modified data file is app/data/index.json which was generated using index.json (and cleaner.py:regroup_weappon), this works but it might be a good policy to recreate if from the original files and a complete rerun of cleaner.py.

### CODE REVIEW

**Comment by Araamarmorth** [comment]
I don't know enough about how exactly you process the unit to tell but I slightly simplified and made more resilient the tech tier part of the sorting of unit so this could be problematic in some special cases. Please tell me if you have any problem with that.

**Comment by JeroenDeDauw** [comment]
Needs manual rebase.

I'd like to see this improvement happen as well \o/

**Comment by spooky** [comment]
Ok, let's pull this in. I just have one suggestion though - instead of a new row in the weapon details with "number of weapons" why not just make a "x{{number of weapons}}" next to the weapon name and show this only if > 1 (or even show for only 1 as well - I guess that will depend on how this will look like with "x1" all over the place). The goal is to reduce the number of "rows" displayed without actually reducing the amount of information.

Also, please rebase :)

**Comment by Araamarmorth** [comment]
Changed into #46 for technical reason.

**Pull request closed without merging**
