### PR TITLE
Add support for the Nomads faction

### PR DESCRIPTION
**Pull request by Exotic-Retard**
This is me attempting to add Nomads, the fifth faction to this DB. i dont really know what im doing, so i would like to ask you to do it instead! However rather than just asking, i did as much work that i could think of myself.

This is rather untested and probably wont work but hopefully it will make things a lot easier once they are finished. Either you could do that, or you could tell me whats broken and then i could do that!

### CODE REVIEW

**Comment by spooky** [comment]
I love the honesty ;)
Haven't had the time to look at this yet, but as soon as I find some I will.
I've been thinking about adding nomads for a while now, but truth be told, the current version doesn't really play nice with that (I mean layout-wise)... buuut... have a look at this: https://faf-unitdb.web.app/faf/list-by-faction
That dropdown on the top-left is there to host stats on any mod (or version of a mod) so maybe would be better to put the effort in the newer version?

**Comment by Exotic-Retard** [comment]
oh hey that one looks pretty great! whats got me confused is where the source repo is, since it seems to link to this one but it doesnt seem like this repo has code for two websites

It would also make it easier i guess since you dont need to PS the faction background for nomads as much :D

**Comment by spooky** [comment]
https://pasteboard.co/Jg9sfPs.jpg
I think we need smaller images :P and also... that does not look like the nomads logo :P
The images used are the work of this guy: https://www.deviantart.com/cb260. I think I tried to contact him about making another one for nomads or sending the template but got no response :/

**Comment by Exotic-Retard** [comment]
im amazed the rest of its working though. ill resize the images and PS a nomads logo together. Is there anything else broken that i can fix?

**Comment by Exotic-Retard** [comment]
Anyway, thats all i can do this time around (without further handholding), let me know what else needs fixing :>

**Comment by spooky** [comment]
Nice. I haven't looked at the functionality yet so I don't really know if it's "working" but, we'll get to that ;)

**Comment by spooky** [comment]
The source for version 2 is not up yet, but will be.
I pulled the changes and looks ok, except for one thing - the white outer glow that's present in all the units (not a fan of it but for consistency's sake...) seems to be missing on most nomad thumbs, can you update that?

**Pull request merged**
